language: c++
matrix:
  include:
  - os: linux
    dist: bionic
    sudo: true
    compiler: gcc
    addons:
      apt:
        packages:
          - gcc
          - gobjc++
          - gnustep
          - cmake
          - make
script: travis/build.sh